// <auto-generated />
namespace CarShowRoom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addorder));
        
        string IMigrationMetadata.Id
        {
            get { return "202103260919580_add-order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
